# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: cr.yandex/crpf54cr0riqft8f2ts1/kafka_postgresql_service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2025-02-17-r2"

containerPort: 5000

config:
  KAFKA_HOST: "rc1a-m4l6n5pdrkm92sb9.mdb.yandexcloud.net"
  KAFKA_PORT: "9091"
  KAFKA_CONSUMER_USERNAME: "producer_consumer"
  KAFKA_CONSUMER_PASSWORD: "Wpbgpn1o0SYxcFBFFRAh"
  KAFKA_CONSUMER_GROUP: "main-consumer-group"
  KAFKA_SOURCE_TOPIC: "transaction-service-input"
  
  PG_WAREHOUSE_HOST: "rc1b-7t9glowuyz9e2yz6.mdb.yandexcloud.net"
  PG_WAREHOUSE_PORT: "6432"
  PG_WAREHOUSE_DBNAME: "sprint9dwh"
  PG_WAREHOUSE_USER: "db_user"
  PG_WAREHOUSE_PASSWORD: "Wpbgpn1o0SYxcFBFFRAh"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
